Repository jordanopensource/nuha-web, pull requests merged in 2023-10, with the labels that each got.

#72 Feat/hero methodology section
  components/Hero/Methodology/Card.vue
  components/Hero/Methodology/index.vue
  components/Hero/Waitlist.vue
  components/Hero/index.vue
  components/Statistics/Indicator.vue
  components/Statistics/index.vue
  lang/ar.ts
  lang/en.ts
  pages/index.vue
  public/images/nuha-meth-1.svg
  public/images/nuha-meth-2.svg
  public/images/nuha-meth-3.svg
Labels: feature

#77 fix: fixed the outlook safe link issue
  server/middleware/auth.ts
Labels: bug

#79 patch: added custom html and text concidering locales
  server/api/auth/[...].ts
Labels: enhancement

#85 Feature: methodology redesign
  components/Hero/Methodology/index.vue
  components/Methodology/Content.vue
  components/Methodology/Hero.vue
  components/Methodology/Section/About.vue
  components/Methodology/Section/Details.vue
  components/Methodology/Section/Ethics.vue
  lang/ar.ts
  lang/en.ts
  pages/methodology/index.vue
  public/images/methodology-cycle.png
  yarn.lock
Labels: enhancement, feature

#86 Refactor: login page
  pages/login/index.vue
Labels: enhancement

#90 Update site fonts
  assets/css/fonts/ibm-plex-sans-arabic.css
  assets/css/fonts/ibm-plex.css
  assets/css/fonts/lt-zarid-serif.css
  assets/css/global.css
  assets/css/tailwind.css
  assets/fonts/IBM-Plex-Mono/IBMPlexMono-Bold.woff2
  assets/fonts/IBM-Plex-Mono/IBMPlexMono-BoldItalic.woff2
  assets/fonts/IBM-Plex-Mono/IBMPlexMono-ExtraLight.woff2
  assets/fonts/IBM-Plex-Mono/IBMPlexMono-ExtraLightItalic.woff2
  assets/fonts/IBM-Plex-Mono/IBMPlexMono-Italic.woff2
  assets/fonts/IBM-Plex-Mono/IBMPlexMono-Light.woff2
  assets/fonts/IBM-Plex-Mono/IBMPlexMono-LightItalic.woff2
  assets/fonts/IBM-Plex-Mono/IBMPlexMono-Medium.woff2
  assets/fonts/IBM-Plex-Mono/IBMPlexMono-MediumItalic.woff2
  assets/fonts/IBM-Plex-Mono/IBMPlexMono-Regular.woff2
  assets/fonts/IBM-Plex-Mono/IBMPlexMono-SemiBold.woff2
  assets/fonts/IBM-Plex-Mono/IBMPlexMono-SemiBoldItalic.woff2
  assets/fonts/IBM-Plex-Mono/IBMPlexMono-Text.woff2
  assets/fonts/IBM-Plex-Mono/IBMPlexMono-TextItalic.woff2
  assets/fonts/IBM-Plex-Mono/IBMPlexMono-Thin.woff2
  assets/fonts/IBM-Plex-Mono/IBMPlexMono-ThinItalic.woff2
  assets/fonts/LT-ZaridSerif-Rg/LT-ZaridSerif-Rg.ttf
  components/Hero/Methodology/Card.vue
  components/Hero/Methodology/index.vue
  components/Hero/index.vue
  components/Methodology/Hero.vue
  components/Methodology/Section/About.vue
  components/Ui/AppHeader/MenuItems/index.vue
  components/Ui/AppHeader/index.vue
  components/Ui/Footer.vue
  components/UserMenu/Button.vue
  nuxt.config.ts
  pages/login/index.vue
  tailwind.config.js
Labels: enhancement, feature

#91 Add charts
  components/Charts/Bar.vue
  components/Charts/Legend.vue
  components/Charts/Pie.vue
  components/Dashboard/Result.vue
  components/Dashboard/Upload/index.vue
  components/Ui/BarChart.vue
  components/Ui/PieChart.vue
  lang/ar.ts
  lang/en.ts
  package.json
  yarn.lock
Labels: enhancement, feature

#92 Patch/update results component
  assets/css/global.css
  components/Charts/Legend.vue
  components/Dashboard/Hero.vue
  components/Dashboard/Result.vue
  components/Dashboard/Upload/index.vue
  components/Ui/AppHeader/MenuItems/index.vue
  components/Ui/AppHeader/index.vue
  components/Upload/index.vue
  composables/useResultsData.ts
  lang/ar.ts
  lang/en.ts
  pages/dashboard/results.vue
  pages/login/index.vue
  server/api/upload-comment.post.ts
  server/api/upload-file.post.ts
  tailwind.config.js
  yarn.lock
Labels: enhancement

#96 Fix/update locale hyperlinks
  components/Hero/Methodology/index.vue
  components/Ui/AppHeader/MenuItems/index.vue
Labels: enhancement

#97 Task/design fixes
  assets/css/global.css
  components/Dashboard/Result.vue
  components/Dashboard/Upload/File.vue
  components/Dashboard/Upload/Step.vue
  components/Dashboard/Upload/index.vue
  components/Hero/Methodology/Card.vue
  components/Hero/Methodology/index.vue
  components/Hero/index.vue
  components/Methodology/Hero.vue
  components/Methodology/Section/About.vue
  components/Ui/AppHeader/index.vue
  components/Ui/Footer.vue
  components/UserMenu/Button.vue
  lang/ar.ts
  lang/en.ts
  layouts/default.vue
  pages/dashboard/results.vue
  tailwind.config.js
Labels: enhancement

#99 Task/fix minor design issues
  lang/ar.ts
  lang/en.ts
  pages/login/index.vue
  server/api/auth/[...].ts
  server/api/auth/verify-request.get.ts
  tailwind.config.js
Labels: bug
